### ISSUE TITLE
Unimplemented operand for __builtin_return_address and __builtin_frame_address(0)

### ISSUE THREAD

**Issue by tkoenig1** [bagel99/llvm-my66000#41]
Reduced from the gcc testsuite.

The following functions hit an "unimplemented operand" message:

```
void test4() { volatile long a = (long)__builtin_return_address(0); }
```
and
```
void test4() { volatile long a = (long)__builtin_frame_address(0); }
```

I'm not sure that these even make sense on My 66000, it may be enough to just error out on an unimplemented builtin function.

**Comment by bagel99** [comment]
Try commit ccd5046eb072.

**Comment by tkoenig1** [comment]
No ICE, and the assembly looks reasonable.

Thanks!
