### ISSUE TITLE
Replacing a shift with a scaled load

### ISSUE THREAD

**Issue by tkoenig1** [bagel99/llvm-my66000#43]
Just so this isn't forgotten...

```
void foo(int *p, unsigned long a, unsigned long b)
{
    p[a+b+200]=1;
}
```
is currently translated to
```
        add     r2,r2,r3
        sll     r2,r2,<0:2>
        stw     #1,[r2,r1,800]
        ret
```
but could be
```
        add     r2,r2,r3
        stw     #1,[r1,r2<<2,800]
        ret
```

**Comment by bagel99** [comment]
Try again with latest commit e3acd0a206118b47b3ed8ee7f99740f9b32e7e83

**Comment by tkoenig1** [comment]
Works perfectly, code generated is

; %bb.0:                                ; %entry
        add     r2,r2,r3
        stw     #1,[r1,r2<<2,800]
        ret

Thanks!
